from src.models.diagnosis import Diagnosis
from src.models.events import PipelineFailureEvent
from src.models.fixes import FixProposal


def generate_pr_title(event: PipelineFailureEvent, diagnosis: Diagnosis) -> str:
    """Generate a concise PR title."""
    return (
        f"fix({event.affected_table}): {diagnosis.category.value} - "
        f"{event.error_type.value}"
    )


def generate_pr_body(
    event: PipelineFailureEvent,
    diagnosis: Diagnosis,
    proposal: FixProposal,
) -> str:
    """Generate a detailed PR body with diagnosis and fix summary."""
    fix_list = "\n".join(
        f"- **{f.fix_type.value}**: {f.description} (`{f.file_path}`)"
        for f in proposal.fixes
    )

    return (
        f"## Automated Fix\n\n"
        f"**Pipeline**: {event.pipeline_name}\n"
        f"**Task**: {event.task_name}\n"
        f"**Error**: {event.error_message}\n\n"
        f"### Diagnosis\n\n"
        f"**Category**: {diagnosis.category.value}\n"
        f"**Confidence**: {diagnosis.confidence:.0%}\n"
        f"**Explanation**: {diagnosis.explanation}\n\n"
        f"### Evidence\n\n"
        + "\n".join(f"- {e}" for e in diagnosis.evidence)
        + f"\n\n### Fixes Applied\n\n{fix_list}\n\n"
        f"### Risk\n\n"
        + "\n".join(f"- {f.risk_level.value}: {f.description}" for f in proposal.fixes)
        + "\n\n---\n*Generated by Autonomous Data Engineer Agent*"
    )
