"""Seed data: historical events, runs, and sample dbt project files."""

from datetime import datetime, timedelta
from uuid import uuid4

from src.models.events import (
    ErrorType,
    EventSeverity,
    EventSource,
    PipelineFailureEvent,
)

_now = datetime.utcnow()


def _ts(hours_ago: int) -> datetime:
    return _now - timedelta(hours=hours_ago)


HISTORICAL_EVENTS: list[PipelineFailureEvent] = [
    PipelineFailureEvent(
        event_id=uuid4(),
        source=EventSource.DBT,
        severity=EventSeverity.HIGH,
        pipeline_name="daily_orders",
        task_name="stg_orders",
        error_message="column 'discount_amount' not found in source",
        error_type=ErrorType.SCHEMA_MISMATCH,
        affected_table="orders",
        affected_column="discount_amount",
        timestamp=_ts(48),
    ),
    PipelineFailureEvent(
        event_id=uuid4(),
        source=EventSource.DBT,
        severity=EventSeverity.MEDIUM,
        pipeline_name="daily_orders",
        task_name="stg_orders",
        error_message="null value in column 'customer_id' violates not-null constraint",
        error_type=ErrorType.NULL_VIOLATION,
        affected_table="orders",
        affected_column="customer_id",
        timestamp=_ts(36),
    ),
    PipelineFailureEvent(
        event_id=uuid4(),
        source=EventSource.AIRFLOW,
        severity=EventSeverity.HIGH,
        pipeline_name="customer_sync",
        task_name="load_customers",
        error_message="invalid input syntax for type integer: 'abc'",
        error_type=ErrorType.TYPE_MISMATCH,
        affected_table="customers",
        affected_column="age",
        timestamp=_ts(30),
    ),
    PipelineFailureEvent(
        event_id=uuid4(),
        source=EventSource.GREAT_EXPECTATIONS,
        severity=EventSeverity.CRITICAL,
        pipeline_name="daily_orders",
        task_name="validate_orders",
        error_message="unexpected row count: expected 10000, got 150000",
        error_type=ErrorType.VOLUME_ANOMALY,
        affected_table="orders",
        timestamp=_ts(24),
    ),
    PipelineFailureEvent(
        event_id=uuid4(),
        source=EventSource.DBT,
        severity=EventSeverity.MEDIUM,
        pipeline_name="payment_pipeline",
        task_name="stg_payments",
        error_message="relation 'raw.payment_methods' does not exist",
        error_type=ErrorType.SCHEMA_MISMATCH,
        affected_table="payment_methods",
        timestamp=_ts(20),
    ),
    PipelineFailureEvent(
        event_id=uuid4(),
        source=EventSource.AIRFLOW,
        severity=EventSeverity.LOW,
        pipeline_name="daily_orders",
        task_name="extract_orders",
        error_message="connection timed out after 30s",
        error_type=ErrorType.TIMEOUT,
        affected_table="orders",
        timestamp=_ts(18),
    ),
    PipelineFailureEvent(
        event_id=uuid4(),
        source=EventSource.CUSTOM,
        severity=EventSeverity.HIGH,
        pipeline_name="user_pipeline",
        task_name="load_users",
        error_message="permission denied for table users",
        error_type=ErrorType.PERMISSION_ERROR,
        affected_table="users",
        timestamp=_ts(16),
    ),
    PipelineFailureEvent(
        event_id=uuid4(),
        source=EventSource.DBT,
        severity=EventSeverity.MEDIUM,
        pipeline_name="daily_orders",
        task_name="fct_orders",
        error_message="column 'shipping_cost' not found",
        error_type=ErrorType.SCHEMA_MISMATCH,
        affected_table="orders",
        affected_column="shipping_cost",
        timestamp=_ts(14),
    ),
    PipelineFailureEvent(
        event_id=uuid4(),
        source=EventSource.DBT,
        severity=EventSeverity.HIGH,
        pipeline_name="customer_sync",
        task_name="dim_customers",
        error_message="null value in column 'email' violates not-null constraint",
        error_type=ErrorType.NULL_VIOLATION,
        affected_table="customers",
        affected_column="email",
        timestamp=_ts(12),
    ),
    PipelineFailureEvent(
        event_id=uuid4(),
        source=EventSource.AIRFLOW,
        severity=EventSeverity.MEDIUM,
        pipeline_name="payment_pipeline",
        task_name="transform_payments",
        error_message="cannot cast 'N/A' to numeric",
        error_type=ErrorType.TYPE_MISMATCH,
        affected_table="payments",
        affected_column="amount",
        timestamp=_ts(10),
    ),
    PipelineFailureEvent(
        event_id=uuid4(),
        source=EventSource.DBT,
        severity=EventSeverity.HIGH,
        pipeline_name="daily_orders",
        task_name="stg_orders",
        error_message="missing column 'tax_rate' in upstream source",
        error_type=ErrorType.SCHEMA_MISMATCH,
        affected_table="orders",
        affected_column="tax_rate",
        timestamp=_ts(8),
    ),
    PipelineFailureEvent(
        event_id=uuid4(),
        source=EventSource.GREAT_EXPECTATIONS,
        severity=EventSeverity.LOW,
        pipeline_name="customer_sync",
        task_name="validate_customers",
        error_message="volume anomaly: 0 rows loaded",
        error_type=ErrorType.VOLUME_ANOMALY,
        affected_table="customers",
        timestamp=_ts(6),
    ),
    PipelineFailureEvent(
        event_id=uuid4(),
        source=EventSource.AIRFLOW,
        severity=EventSeverity.CRITICAL,
        pipeline_name="daily_orders",
        task_name="publish_orders",
        error_message="deadline exceeded: downstream consumer not responding",
        error_type=ErrorType.TIMEOUT,
        affected_table="orders",
        timestamp=_ts(5),
    ),
    PipelineFailureEvent(
        event_id=uuid4(),
        source=EventSource.DBT,
        severity=EventSeverity.MEDIUM,
        pipeline_name="payment_pipeline",
        task_name="stg_payments",
        error_message="source 'raw_payments' not found in schema",
        error_type=ErrorType.MISSING_SOURCE,
        affected_table="payments",
        timestamp=_ts(4),
    ),
    PipelineFailureEvent(
        event_id=uuid4(),
        source=EventSource.CUSTOM,
        severity=EventSeverity.LOW,
        pipeline_name="daily_orders",
        task_name="audit_check",
        error_message="assertion failed: order total != sum of line items",
        error_type=ErrorType.LOGIC_ERROR,
        affected_table="orders",
        timestamp=_ts(3),
    ),
    PipelineFailureEvent(
        event_id=uuid4(),
        source=EventSource.DBT,
        severity=EventSeverity.HIGH,
        pipeline_name="daily_orders",
        task_name="stg_orders",
        error_message="column 'promo_code' not found after upstream migration",
        error_type=ErrorType.SCHEMA_MISMATCH,
        affected_table="orders",
        affected_column="promo_code",
        timestamp=_ts(2),
    ),
    PipelineFailureEvent(
        event_id=uuid4(),
        source=EventSource.AIRFLOW,
        severity=EventSeverity.MEDIUM,
        pipeline_name="customer_sync",
        task_name="extract_customers",
        error_message="access denied to s3://data-lake/customers/",
        error_type=ErrorType.PERMISSION_ERROR,
        affected_table="customers",
        timestamp=_ts(2),
    ),
    PipelineFailureEvent(
        event_id=uuid4(),
        source=EventSource.DBT,
        severity=EventSeverity.MEDIUM,
        pipeline_name="payment_pipeline",
        task_name="stg_payments",
        error_message="null value in column 'payment_method' violates not-null",
        error_type=ErrorType.NULL_VIOLATION,
        affected_table="payments",
        affected_column="payment_method",
        timestamp=_ts(1),
    ),
    PipelineFailureEvent(
        event_id=uuid4(),
        source=EventSource.GREAT_EXPECTATIONS,
        severity=EventSeverity.HIGH,
        pipeline_name="daily_orders",
        task_name="validate_orders",
        error_message="schema mismatch: 3 new columns detected in source",
        error_type=ErrorType.SCHEMA_MISMATCH,
        affected_table="orders",
        timestamp=_ts(1),
    ),
    PipelineFailureEvent(
        event_id=uuid4(),
        source=EventSource.DBT,
        severity=EventSeverity.LOW,
        pipeline_name="daily_orders",
        task_name="fct_orders",
        error_message="division by zero in margin calculation",
        error_type=ErrorType.LOGIC_ERROR,
        affected_table="orders",
        affected_column="margin",
        timestamp=_ts(0),
    ),
]

SAMPLE_RUNS: list[dict] = [
    {
        "run_id": str(uuid4()),
        "event_id": str(e.event_id),
        "pipeline": e.pipeline_name,
        "status": "completed" if i % 3 != 0 else "escalated",
    }
    for i, e in enumerate(HISTORICAL_EVENTS[:10])
]
