"""Schema contract tests for database and model consistency.

This test suite validates that:
1. TradeAggregate model fields match database columns
2. DatabaseWriter UPSERT SQL includes all persisted fields
3. Field types and constraints are consistent

This prevents drift when fields are added to the model but not to the database or SQL.
"""

import re
from datetime import datetime, timezone
from decimal import Decimal

import pytest

from src.common.models import TradeAggregate
from src.consumer.db_writer import DatabaseWriter


class TestSchemaContract:
    """Validate schema contracts between model, database, and SQL statements."""

    # Fields that exist in TradeAggregate but are NOT persisted to database
    # These are calculation-only or intermediate fields
    MODEL_ONLY_FIELDS = {"total_value"}  # Used for VWAP calculation, not stored

    # Fields that are auto-generated by database (not in INSERT VALUES)
    DB_AUTO_FIELDS = {"created_at", "updated_at"}

    # Expected persisted fields in TradeAggregate (excluding model-only fields)
    EXPECTED_PERSISTED_FIELDS = {
        # Primary key components
        "symbol",
        "window_start",
        "window_end",
        # Core aggregates
        "vwap",
        "total_volume",
        "trade_count",
        "max_price",
        "min_price",
        # LMP pricing components
        "lmp",
        "lmp_energy",
        "lmp_congestion",
        "lmp_loss",
    }

    @pytest.fixture
    def sample_aggregate(self) -> TradeAggregate:
        """Create a sample TradeAggregate for testing."""
        return TradeAggregate(
            symbol="POWER_DE",
            window_start=datetime(2024, 1, 1, 12, 0, 0, tzinfo=timezone.utc),
            window_end=datetime(2024, 1, 1, 12, 1, 0, tzinfo=timezone.utc),
            vwap=Decimal("100.50"),
            total_volume=Decimal("1000.0"),
            trade_count=10,
            max_price=Decimal("105.0"),
            min_price=Decimal("95.0"),
            total_value=Decimal("100500.0"),  # Calculation-only field
            lmp=Decimal("102.0"),
            lmp_energy=Decimal("100.0"),
            lmp_congestion=Decimal("1.5"),
            lmp_loss=Decimal("0.5"),
        )

    def test_model_has_all_expected_fields(self, sample_aggregate: TradeAggregate):
        """Verify TradeAggregate model has all expected persisted fields."""
        model_fields = set(sample_aggregate.model_fields.keys())

        # Check that all expected persisted fields exist in the model
        missing_fields = self.EXPECTED_PERSISTED_FIELDS - model_fields
        assert not missing_fields, (
            f"TradeAggregate model is missing expected fields: {missing_fields}"
        )

        # Verify model-only fields are documented
        for field in self.MODEL_ONLY_FIELDS:
            assert field in model_fields, (
                f"MODEL_ONLY_FIELDS includes '{field}' but it doesn't exist in model"
            )

    def test_upsert_sql_includes_all_persisted_fields(self):
        """Verify UPSERT SQL includes all persisted fields (excluding auto-generated)."""
        upsert_sql = DatabaseWriter.UPSERT_AGGREGATE_SQL

        # Extract field names from INSERT clause
        insert_match = re.search(
            r"INSERT INTO trade_aggregates\s*\((.*?)\)",
            upsert_sql,
            re.DOTALL | re.IGNORECASE,
        )
        assert insert_match, "Could not parse INSERT clause from UPSERT SQL"

        insert_fields = {
            field.strip()
            for field in insert_match.group(1).split(",")
            if field.strip()
        }

        # Expected fields in SQL = persisted fields + auto-generated fields
        expected_sql_fields = self.EXPECTED_PERSISTED_FIELDS | self.DB_AUTO_FIELDS

        # Check for missing fields
        missing_in_sql = expected_sql_fields - insert_fields
        assert not missing_in_sql, (
            f"UPSERT SQL is missing these fields: {missing_in_sql}\n"
            f"These fields exist in the model/schema but are not in the INSERT statement.\n"
            f"Update DatabaseWriter.UPSERT_AGGREGATE_SQL to include them."
        )

        # Check for extra fields (fields in SQL but not expected)
        extra_in_sql = insert_fields - expected_sql_fields
        assert not extra_in_sql, (
            f"UPSERT SQL has unexpected fields: {extra_in_sql}\n"
            f"These fields are in the SQL but not in the model or are deprecated."
        )

    def test_upsert_sql_has_matching_values_placeholders(self):
        """Verify UPSERT SQL VALUES clause has placeholders for all INSERT fields."""
        upsert_sql = DatabaseWriter.UPSERT_AGGREGATE_SQL

        # Extract INSERT field names
        insert_match = re.search(
            r"INSERT INTO trade_aggregates\s*\((.*?)\)",
            upsert_sql,
            re.DOTALL | re.IGNORECASE,
        )
        assert insert_match, "Could not parse INSERT clause"
        insert_fields = [
            field.strip() for field in insert_match.group(1).split(",") if field.strip()
        ]

        # Extract VALUES placeholders
        values_match = re.search(
            r"VALUES\s*\((.*?)\)",
            upsert_sql,
            re.DOTALL | re.IGNORECASE,
        )
        assert values_match, "Could not parse VALUES clause"
        values_placeholders = [
            val.strip() for val in values_match.group(1).split(",") if val.strip()
        ]

        # Count should match
        assert len(insert_fields) == len(values_placeholders), (
            f"INSERT fields count ({len(insert_fields)}) != VALUES count ({len(values_placeholders)})\n"
            f"INSERT: {insert_fields}\n"
            f"VALUES: {values_placeholders}"
        )

        # Check for %(field)s pattern for non-auto fields
        for field in insert_fields:
            if field not in self.DB_AUTO_FIELDS:
                expected_placeholder = f"%({field})s"
                assert expected_placeholder in values_placeholders, (
                    f"Missing placeholder for field '{field}': expected '{expected_placeholder}'"
                )

    def test_upsert_sql_on_conflict_updates_all_mutable_fields(self):
        """Verify ON CONFLICT DO UPDATE includes all fields that can change."""
        upsert_sql = DatabaseWriter.UPSERT_AGGREGATE_SQL

        # Extract ON CONFLICT DO UPDATE SET clause
        conflict_match = re.search(
            r"ON CONFLICT.*?DO UPDATE SET(.*?)(?:$|;)",
            upsert_sql,
            re.DOTALL | re.IGNORECASE,
        )
        assert conflict_match, "Could not parse ON CONFLICT clause"

        update_fields = {
            field.split("=")[0].strip()
            for field in conflict_match.group(1).split(",")
            if "=" in field
        }

        # Expected updateable fields (all persisted except primary key components)
        pk_fields = {"symbol", "window_start"}
        expected_update_fields = self.EXPECTED_PERSISTED_FIELDS - pk_fields

        # Check for missing updates
        missing_updates = expected_update_fields - update_fields
        assert not missing_updates, (
            f"ON CONFLICT UPDATE is missing these fields: {missing_updates}\n"
            f"When a window is reprocessed, these fields should be updated."
        )

    def test_write_aggregates_batch_prepares_correct_params(self):
        """Verify UPSERT SQL placeholders cover all persisted fields."""
        upsert_sql = DatabaseWriter.UPSERT_AGGREGATE_SQL

        # Extract placeholder names from VALUES clause (%(name)s pattern)
        placeholder_names = set(re.findall(r"%\((\w+)\)s", upsert_sql))

        # Every persisted field (excluding auto-generated) must have a placeholder
        expected_in_params = self.EXPECTED_PERSISTED_FIELDS - self.DB_AUTO_FIELDS

        missing_placeholders = expected_in_params - placeholder_names
        assert not missing_placeholders, (
            f"UPSERT SQL VALUES is missing placeholders for: {missing_placeholders}\n"
            f"Add %(field_name)s entries to the VALUES clause in UPSERT_AGGREGATE_SQL."
        )

        extra_placeholders = placeholder_names - expected_in_params
        assert not extra_placeholders, (
            f"UPSERT SQL VALUES has unexpected placeholders: {extra_placeholders}\n"
            f"Remove them from the VALUES clause or add to EXPECTED_PERSISTED_FIELDS."
        )

    def test_to_db_tuple_includes_all_persisted_fields(self, sample_aggregate: TradeAggregate):
        """Verify TradeAggregate.to_db_tuple() returns all persisted fields in correct order."""
        db_tuple = sample_aggregate.to_db_tuple()

        # Expected fields in order (based on current implementation)
        expected_fields = [
            "symbol",
            "window_start",
            "window_end",
            "vwap",
            "total_volume",
            "trade_count",
            "max_price",
            "min_price",
            "lmp",
            "lmp_energy",
            "lmp_congestion",
            "lmp_loss",
        ]

        # Tuple length should match
        assert len(db_tuple) == len(expected_fields), (
            f"to_db_tuple() returns {len(db_tuple)} values, expected {len(expected_fields)}\n"
            f"Expected fields: {expected_fields}"
        )

        # Verify values are correct (basic smoke test)
        assert db_tuple[0] == sample_aggregate.symbol
        assert db_tuple[3] == sample_aggregate.vwap
        assert db_tuple[8] == sample_aggregate.lmp

        # Verify no total_value in tuple (it's model-only)
        assert sample_aggregate.total_value not in db_tuple, (
            "to_db_tuple() should not include 'total_value' (model-only field)"
        )

    def test_model_only_fields_are_not_persisted(self, sample_aggregate: TradeAggregate):
        """Verify model-only fields are documented and not included in SQL."""
        upsert_sql = DatabaseWriter.UPSERT_AGGREGATE_SQL

        for field in self.MODEL_ONLY_FIELDS:
            # Field should exist in model
            assert field in sample_aggregate.model_fields, (
                f"MODEL_ONLY_FIELDS includes '{field}' but it's not in the model"
            )

            # Field should NOT be in SQL
            assert field not in upsert_sql.lower(), (
                f"Model-only field '{field}' should not appear in UPSERT SQL"
            )

    def test_nullable_lmp_fields_have_defaults(self):
        """Verify LMP fields are nullable for backward compatibility."""
        # Create aggregate without LMP fields
        agg_without_lmp = TradeAggregate(
            symbol="POWER_DE",
            window_start=datetime(2024, 1, 1, 12, 0, 0, tzinfo=timezone.utc),
            window_end=datetime(2024, 1, 1, 12, 1, 0, tzinfo=timezone.utc),
            vwap=Decimal("100.50"),
            total_volume=Decimal("1000.0"),
            trade_count=10,
            max_price=Decimal("105.0"),
            min_price=Decimal("95.0"),
            total_value=Decimal("100500.0"),
            # LMP fields omitted
        )

        # LMP fields should default to None
        assert agg_without_lmp.lmp is None
        assert agg_without_lmp.lmp_energy is None
        assert agg_without_lmp.lmp_congestion is None
        assert agg_without_lmp.lmp_loss is None

    def test_database_schema_matches_model(self):
        """Document the expected database schema for trade_aggregates table.

        This is a documentation test - it doesn't connect to the database,
        but ensures the schema is clearly defined and matches the model.
        """
        # Expected database columns (from 001_create_trade_aggregates.sql + 004_add_lmp_columns.sql)
        expected_db_columns = {
            # Primary key
            "symbol": "VARCHAR(20)",
            "window_start": "TIMESTAMPTZ",
            # Aggregates
            "window_end": "TIMESTAMPTZ",
            "vwap": "NUMERIC(18, 8)",
            "total_volume": "NUMERIC(18, 8)",
            "trade_count": "INTEGER",
            "max_price": "NUMERIC(18, 8)",
            "min_price": "NUMERIC(18, 8)",
            # LMP components (nullable)
            "lmp": "NUMERIC(18, 8)",
            "lmp_energy": "NUMERIC(18, 8)",
            "lmp_congestion": "NUMERIC(18, 8)",
            "lmp_loss": "NUMERIC(18, 8)",
            # Audit fields
            "created_at": "TIMESTAMPTZ",
            "updated_at": "TIMESTAMPTZ",
        }

        # All persisted model fields should have corresponding DB columns
        missing_columns = self.EXPECTED_PERSISTED_FIELDS - set(expected_db_columns.keys())
        assert not missing_columns, (
            f"Model has persisted fields without database columns: {missing_columns}\n"
            f"Add these columns to sql/schema/ migration."
        )

        # Document that total_value is NOT in database
        assert "total_value" not in expected_db_columns, (
            "total_value should not be in database (it's a calculation-only field)"
        )
